# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Miners',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('status', models.CharField(default=1, editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miners', to_field='id'),
        ),
    ]
